Feature/2017 10 24 blogpost kickstarters 2017
ordina-ncore/ordina-ncore.github.io pull request #37
Opened 2017-10-24 10:38 UTC by JeroenVanWolput

Added the blogpost and jeroen van wolput as an author

2017-10-25 08:49 UTC, JeroenRombouts commented
Are you waiting for a review? If so: you can add reviewers on the right....

2017-10-25 17:22 UTC, jensg requested changes

2017-10-25 17:22 UTC, jensg commented on _posts/2017-10-24-jeroen-van-wolput-kickstarters-2017.md
> +**The first day of a journey will always be remembered. On august 1st over 40 open minded and enthusiastic kickstarters embarked on a journey into the unknown. A journey filled with mountains to clim
> **One of those teams** sprouted a team of 6 dedicated travelers
There is a reference to a team without mentioning a team first.

2017-10-25 17:22 UTC, jensg commented on _posts/2017-10-24-jeroen-van-wolput-kickstarters-2017.md
> +![The new Kickstarters](/img/kickstarters2017/kickstartersGroup.JPG "The new Kickstarters")
Maybe leave out this image?

2017-10-26 08:21 UTC, JeroenVanWolput commented on _posts/2017-10-24-jeroen-van-wolput-kickstarters-2017.md
> +![The new Kickstarters](/img/kickstarters2017/kickstartersGroup.JPG "The new Kickstarters")
Leave the image with Sami in?

2017-10-26 09:32 UTC, jensg approved these changes

2017-10-26 09:33 UTC, merged